name: Continuous Integration

env:
  GH_TOKEN: ${{ github.token }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: write
  contents: read
  id-token: write
  issues: read
  packages: read
  pull-requests: read
  repository-projects: read

jobs:
  ci:
    #if: github.event.pull_request.draft == false && github.event.pull_request.state == 'open'
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials for access to pipeline data
        uses: aws-actions/configure-aws-credentials@v4.0.0
        with:
          aws-region: us-east-1
          role-skip-session-tagging: true
          role-to-assume: arn:aws:iam::611524785219:role/managed/eh.github-actions.repo.eh-sigma-plugins.role

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Run build
        run: npm run build

      - name: Deploy to S3
        run: aws s3 cp build/ s3://eh-sigma-plugins-host/ --dryrun --recursive

      - name: Invalidate cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id E31RLQWQ6W0U89 --paths '/*'
